config/routes.rb
Rails.application.routes.draw do
  post "add_item", to: 'cart#add_item'
  delete "remove_item", to: 'cart#remove_item'
  get "checkout", to: 'cart#checkout'
  patch "pay_order", to: 'cart#pay_order'
  get 'past_orders', to: 'cart#past_orders'

  patch 'redeem_credit', to: 'welcome#redeem_credit'
  root 'welcome#home'
  resources :products, only: [:index, :show]
  devise_for :users, controllers: {registrations: "registrations"} 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	#Relations
	belongs_to :order
	belongs_to :product
	validates :product, presence: true
	validates :order, presence: true

	def pay
		self.update(total_payed: self.product.price)
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :items
	has_many :products, through: :items

	scope :open, ->{where(purchased_at: nil).first_or_create}
	scope :past, ->{where.not(purchased_at: nil)}

	default_scope ->{order(created_at: :desc)}

	validates :user, presence: true

	def store_cart products
		products.each do |k,v|
			item = self.items.where(product_id: k).first_or_create
			item.update(quantity: v)
		end
	end

	def add_one product_id
		item = self.items.where(product_id: product_id).first_or_create
		item.update(quantity: item.quantity + 1)
	end


	def remove_item product_id, complete=nil
		item = self.items.find_by(product_id: product_id)
		if complete
			item.destroy
		else
			item.quantity > 0 ? item.update(quantity: item.quantity - 1) : item.destroy
		end
	end


	def items_hsh
		self.items.inject({}){|hash, item| hash.merge({item.product_id => item.quantity})}
	end

	def total
		self.total_payed or self.products.sum(&:price)
	end

	def pay_with shipping, method=:credits
		self.items.map(&:pay)
		self.update(total_payed: self.total, purchased_at: Time.now, state: shipping[:state], address: shipping[:address], phone: shipping[:phone])
		self.user.update(credit: self.user.credit - self.total) if method == :credits
	end


end

app/models/product.rb
class Product < ApplicationRecord
	has_many :items
	has_many :orders, through: :items

	validates :name, presence: true
	validates :brand, presence: true
	validates :model, presence: true
	validates :sku, presence: true
	validates :price, presence: true


	def self.opts field
		["All"] + (self.all.pluck(field).uniq ).sort{|a,b| a <=> b}
	end


	def self.search search_params
		results = self
		results = results.where("LOWER(name) LIKE :term OR LOWER(brand) LIKE :term OR LOWER(model) LIKE :term OR LOWER(sku) LIKE :term OR LOWER(price) LIKE :term OR LOWER(desc) LIKE :term", term: "%#{search_params[:term]}%") if search_params[:term]
		results = results.where(brand: search_params[:brand]) if search_params[:brand] and search_params[:brand] != "All"
		results = results.where("price >= :price", price: search_params[:price_from].to_f) if search_params[:price_from].to_f != 0
		results = results.where("price <= :price", price: search_params[:price_to].to_f) if search_params[:price_to].to_f != 0
		results.all
	end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :orders


  validates :fullname, presence: true
    

  def redeem_credit
  	self.update(credit: 10000, bonus_given: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :my_cart

  protected
  def my_cart
  	if session[:items]
  		session[:items]
  	else
  		user_signed_in? ? current_user.orders.open.items_hsh : {}
  	end
  end


  def after_sign_in_path_for(resource_or_scope)
		current_user.orders.open.store_cart session[:items] if session[:items]
		session[:items] = nil
		super
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_action :authenticate_user!, only: [:checkout]

  def add_item
  	if user_signed_in?
  		@order = current_user.orders.open
  		@order.add_one(params[:id])
  	else
  		session[:items] ||= {}
  		session[:items][params[:id]] ||= 0
  		session[:items][params[:id]] += 1
  	end
  end

  def remove_item
    if user_signed_in?
      @order = current_user.orders.open
      @order.remove_item(params[:id], params[:complete])
    else
      if session[:items][params[:id]] == 0 or params[:complete]
        session[:items].except!(params[:id])
      else
        session[:items][params[:id]] -= 1
      end
    end
  end

  def checkout
    redirect_to products_path unless my_cart.any?
    @order = current_user.orders.open
  end

  def pay_order
    case params[:payment]
    when 1, "1"
      current_user.orders.open.pay_with(shipping_params, :credits)
    end
    redirect_to past_orders_path
  end

  def past_orders
    @orders = current_user.orders.past.to_a
    @recent_order = @orders.shift
  end
  protected

  def shipping_params
  	params.permit(:state, :address, :phone)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.search(search_params)
  end

  def show
  	@product = Product.find(params[:id])
  end


  protected
  	def search_params
  		params.permit(:term, :brand, :price_from, :price_to)
  	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, only: [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:fullname, :email, :password, :address, :state, :phone) }
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:home]
  def home
    @products = Product.search(search_params)
  end

  def redeem_credit
  	current_user.redeem_credit unless current_user.bonus_given
  	redirect_to :back
  end

  protected
  	def search_params
  		params.permit(:term, :brand, :price_from, :price_to)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def home?
		controller.controller_name == "welcome" and controller.action_name == "home"
	end

	def products?
		controller.controller_name == "products"
	end

	def past_orders?
		controller.controller_name == "cart" and controller.action_name == "past_orders"
	end
end

app/helpers/cart_helper.rb
module CartHelper

	def sum_total
		total = 0
		my_cart.each do |item,quantity|
			total += subtotal(item, quantity)
		end
		total
	end

end

app/helpers/products_helper.rb
module ProductsHelper


	def product_name id
		Product.find(id).name
	end


	def subtotal id, quantity
		Product.find(id).price * quantity
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cart/_index.html.erb
<div class="ui floating dropdown icon button yellow cart" data-element="dropdown" data-type="module">
	<span class="text"><i class="shop icon"></i> View Cart</span>

	<div class="menu transition hidden">
		<div class="item">
			<div class="inner">
				<table class="ui table">
					<thead>
						<tr>
							<th>Product</th>
							<th>Quantity</th>
							<th>Price</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<%= render "cart/items_rows" %>
					</tbody>
				</table>
			</div>
			<% if my_cart.any? %>
				<hr>
				<%= link_to "Checkout", checkout_path, class: "ui button green"  %>
			<% end %>
		</div>

	</div>
</div>

app/views/cart/_items_rows.html.erb
<% 	my_cart.each do |item,quantity| %>
	<tr id="item-<%= item %>">
		<td><%= product_name item %></td>
		<td><%= quantity %></td>
		<td><%= number_to_currency subtotal(item, quantity) %></td>
		<td>
			<%= link_to raw("<i class='minus icon'></i>"), remove_item_path(id: item), remote: true, class: "mini ui icon button teal", title: "Remove one", method: :delete if quantity > 1 %>
			<%= link_to raw("<i class='remove icon'></i>"), remove_item_path(id: item, complete: true), remote: true, class: "mini ui icon button red", title: "Remove product", method: :delete %>
		</td>
	</tr>
<% end %>
<tr>
	<td colspan="2"><b>TOTAL:</b></td>
	<td colspan="2"><b><%= number_to_currency sum_total %></b></td>
</tr>

app/views/cart/_order.html.erb
<div class="title <%= 'active' if active %>">
	<i class="dropdown icon"></i>
	<%= order.purchased_at.strftime("%m/%d/%Y") %>: <em><%= number_to_currency order.total %></em>
</div>
<div class="content <%= 'active' if active %>">
	<b>Your order was  shipped to:</b>
	<dl>
		<dt><%= order.state %></dt>
		<dt><%= order.address %></dt>
		<dt><%= order.phone %></dt>
	</dl>
	<table class="ui table">
		<thead>
			<tr>
				<th>Product</th>
				<th>Quantity</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			<% order.items.each do |item| %>
				<tr>
					<td><%= item.product.name %></td>
					<td><%= item.quantity %></td>
					<td><%= number_to_currency item.total_payed %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/cart/add_item.js.erb
$(".ui.floating.cart").replaceWith("<%= j render 'cart/index' %>");
$('.ui.dropdown').dropdown();
$(".ui.floating").click();
$('.ui.modal').modal('hide');

app/views/cart/checkout.html.erb
<h1>Please review the items you are about to purchase</h1>

<table class="ui table">
	<thead>
		<tr>
			<th>Product</th>
			<th>Quantity</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		<% @order.items.each do |item| %>
			<tr>
				<td><%= item.product.name %></td>
				<td><%= item.quantity %></td>
				<td><%= number_to_currency(item.product.price * item.quantity)%></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="2"><b>TOTAL:</b></td>
			<td><%= number_to_currency @order.total %></td>
		</tr>
	</tbody>
</table>

<% if @order.total <= current_user.credit %>
	<%= form_tag pay_order_path, method: :patch, class: "ui form" do %>
		<h4>Please confirm your shipping address and your payment method</h4>
		<div class="ui two column grid">
			<div class="column">
				<%= select_tag :state, options_for_select(CS.states(:us).values, current_user.state), class: "ui search dropdown", required: true %>
			</div>
			<div class="column">
				<%= text_field_tag :address, current_user.address, required: true %>
			</div>
			<div class="column">
				<%= text_field_tag :phone, current_user.phone, required: true %>
			</div>
			<div class="column">
				<%= select_tag :payment, options_for_select([["My credit #{number_to_currency current_user.credit}", 1]]), prompt: "Select Payment Method", class: "ui dropdown" %>
			</div>
			<div class="column">
				<%= button_tag raw("<i class='dollar icon'></i> Pay Now"), type: "submit", class: "ui icon button green"%>
			</div>
		</div>
	<% end %>
<% else %>
	<h4>You don't have enough credits to make this purchase!</h4>
	<%= render "welcome/redeem" %>
<% end %>

app/views/cart/past_orders.html.erb
<h1>These are your past orders</h1>
<div class="ui two column grid">
	<div class="column"> 
		<h3>Recent Order</h3>
		<div class="ui styled accordion">
			<%= render "cart/order", order: @recent_order, active: true %>
		</div>
	</div>
	<div class="column">
		<h3>Past Orders</h3>
		<div class="ui styled accordion">
			<% @orders.each do |order| %>
				<%= render "cart/order", order: order, active: false %>
			<% end %>
		</div>
	</div>
</div>

app/views/cart/remove_item.js.erb
$(".ui.floating.cart").replaceWith("<%= j render 'cart/index' %>");
$('.ui.dropdown').dropdown();
$(".ui.floating").click();

app/views/layouts/_menu.html.erb
<ul class="nav nav-pills">
	<li role="presentation" class="<%= "item #{'active' if home?}" %> ">
		<%= link_to raw(" <i class='home icon'></i>Home"), root_url, class: "item #{'active' if home?}" %>
	</li>
	<li role="presentation" class="<%= "item #{'active' if products?}" %>">
		<%= link_to raw(" <i class='gamepad icon'></i>Products"), products_path, class: "item #{'active' if products?}" %>
	</li>
	<% if user_signed_in? %>
 		<li role="presentation" class="<%= "item #{'active' if !home? && !products?}" %>">
			<i class="dollar icon"></i><%= number_to_currency current_user.credit %>
		</li>
 		<li role="presentation">
		 	<%= link_to raw("<i class='calendar icon'></i>My past orders"), past_orders_path, class: "item #{'active' if past_orders?}" %>
		</li>
		<li role="presentation">
 			<%= link_to raw("<i class='sign out icon'></i>Sign Out"), destroy_user_session_path, method: :delete, class: "item" %>
		</li>
 		<% else %>
 			<li role="presentation">
			 	<%= link_to raw("<i class='sign in icon'></i>Sign In"), new_user_session_path, class: "item" %>
			</li>
 		<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/menu" %>
      <%= render "cart/index" %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    </div>
  </body>
</html>

app/views/products/_list.html.erb
<div id="products" class="row list-group">
	<% @products.each do |product| %>
    <div class="item  col-xs-4 col-lg-4">
        <div class="thumbnail">
            <img class="group list-group-image" src="http://placehold.it/400x250/000/fff" alt="" />
            <div class="caption">
                <h4 class="group inner list-group-item-heading"><%= product.name %></h4>
                    <p class="group inner list-group-item-text">
                        <%= product.brand %>
                    </p>
                    <small> <%= product.model %> </small>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead"><%= number_to_currency product.price %></p>
                        </div>
                    <div class="col-xs-12 col-md-6">
                        <%= link_to product, remote: true, title: "View more", class: "ui button teal" do %>
                            <i class="info circle icon"></i>View Item
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
    <% unless @products.any? %>
		<h4>No results found</h4>
	<% end %>
</div>

app/views/products/_show.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="text-danger fa fa-times"></i></button>
				<h4 class="modal-title" id="myModalLabel"><i class="text-muted fa fa-shopping-cart"></i> <strong><%= @product.sku %></strong> - <%= @product.name %> </h4>
		</div>
		<div class="modal-body">
				<table class="pull-left col-md-8 ">
					<tbody>
							<tr>
								<td class="h6"><strong>SKU</strong></td>
								<td> </td>
								<td class="h5"><b><%= @product.sku %></b></td>
							</tr>
							<tr>
								<td class="h6"><strong>Brand</strong></td>
								<td> </td>
								<td class="h5"><%= @product.brand %></td>
							</tr>
							<tr>
								<td class="h6"><strong>Model</strong></td>
								<td> </td>
								<td class="h5"><%= @product.model %></td>
							</tr>
							<tr>
								<td class="h6"><strong>Description</strong></td>
								<td> </td>
								<td class="h5"><%= @product.desc %></td>
							</tr>
							<tr>
								<td class="h6"><strong>Product Name</strong></td>
								<td> </td>
								<td class="h5"><%= @product.name %></td>
							</tr>
							<tr>
								<td class="h6"><strong>Price</strong></td>
								<td> </td>
								<td class="h5"><%= number_to_currency @product.price %></td>
							</tr>
					</tbody>
				</table>
				<div class="col-md-4"> 
					<img src="/image.png" class="img-responsive img-thumbnail">  
				</div>
				<div class="clearfix"></div>
				<p class="open_info hide"><%= @product.desc %></p>
		</div>
		<div class="modal-footer">
				<div class="text-right pull-right col-md-3">
					<%= link_to raw("<i class='add to cart icon'></i> Add to cart"), add_item_path(id: @product.id), remote: true, method: :post, class: "btn btn-success" %>
				</div>
		</div>
	</div>
</div>

app/views/products/index.html.erb
	
<div class="ui stackable grid">
	<div class="sixteen wide column">
		<h1>Products list</h1>
	</div>
	<%= form_tag products_path, class: "ui form sixteen wide column", method: :get do %>
		<div class="ui stackable grid">
			<div class="five wide column"><%= text_field_tag :term, params[:term], placeholder: "Search by term" %></div>
			<div class="three wide column"><%= select_tag :brand, options_for_select(Product.opts(:brand), (params[:brand] or "All")), class: "ui fluid search dropdown" %></div>
			<div class="three wide column"><%= number_field_tag :price_from, params[:price_from], placeholder: "Prices from", min: 0, step: 0.01 %></div>
			<div class="three wide column"><%= number_field_tag :price_to, params[:price_to], placeholder: "Prices to", min: 0, step: 0.01 %></div>
			<div class="two wide column"><%= button_tag raw("<i class='search icon'></i> Search"), type: "submit", class: "ui icon button green" %></div>
		</div>
	<% end %>
</div>
<%= render "products/list", locals: {products: @products} %>
<hr>
<%= link_to "Go Top", '#', class: "ui button gotop" %>

app/views/products/show.js.erb
jQuery( document ).ready(function() {
    jQuery('#myModal').html("<%= j render 'products/show' %>");
    jQuery('.ui.button.teal').on('click',function(){
        jQuery('#myModal').modal('show');
    });
});

app/views/welcome/_redeem.html.erb
<% if current_user.bonus_given %>
	<p>You currently have <%= number_to_currency current_user.credit %></p>
<% else %>
	<p>It looks like you are a new user. You can redeem some credits as a reward.</p>
	<%= link_to raw("<i class='dollar icon'></i>Redeem my credit"), redeem_credit_path, method: :patch, class: "ui button blue" %>
<% end %>

app/views/welcome/home.html.erb
<h1>Welcome <%= user_signed_in? ? current_user.fullname : " to our store!" %></h1>

<%= render "welcome/redeem" if user_signed_in? %>
<%= render "products/list", locals: {products: @products} %>